AWSTemplateFormatVersion: 2010-09-09
Description: |
  this IAM Role is for EC2 + RDS templates

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  OutputEc2IamRole:
    Type: String
    Default: XXXXX-OutputEc2IamRoleId

  OutputRdsInstanceName:
    Description: input output rds dbname
    Type: String
    Default: XXXXX-OutputRdsId

# ------------------------------------------------------------#
# MetaData
# ------------------------------------------------------------# 
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Output Configuration"
        Parameters:
          - OutputEc2IamRole
          - OutputRdsInstanceName
    
Resources:
  IAMPOLICYID:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
            -
                Sid: SecretsManagerDbCredentialsAccess
                Effect: Allow
                Action:
                    - 'secretsmanager:GetSecretValue'
                    - 'secretsmanager:PutResourcePolicy'
                    - 'secretsmanager:PutSecretValue'
                    - 'secretsmanager:DeleteSecret'
                    - 'secretsmanager:DescribeSecret'
                    - 'secretsmanager:TagResource'
                Resource: 'arn:aws:secretsmanager:*:*:secret:rds-db-credentials/*'
            -
                Sid: RDSDataServiceAccess
                Effect: Allow
                Action:
                    - 'dbqms:CreateFavoriteQuery'
                    - 'dbqms:DescribeFavoriteQueries'
                    - 'dbqms:UpdateFavoriteQuery'
                    - 'dbqms:DeleteFavoriteQueries'
                    - 'dbqms:GetQueryString'
                    - 'dbqms:CreateQueryHistory'
                    - 'dbqms:DescribeQueryHistory'
                    - 'dbqms:UpdateQueryHistory'
                    - 'dbqms:DeleteQueryHistory'
                    - 'rds-data:ExecuteSql'
                    - 'rds-data:ExecuteStatement'
                    - 'rds-data:BatchExecuteStatement'
                    - 'rds-data:BeginTransaction'
                    - 'rds-data:CommitTransaction'
                    - 'rds-data:RollbackTransaction'
                    - 'secretsmanager:CreateSecret'
                    - 'secretsmanager:ListSecrets'
                    - 'secretsmanager:GetRandomPassword'
                    - 'tag:GetResources'
                Resource: {"Fn::ImportValue": !Sub "${OutputRdsInstanceName}"}

      PolicyName: !Sub ${AWS::StackName}-RdsPolicy
      Roles:
        - {"Fn::ImportValue": !Sub "${OutputEc2IamRole}"}
