AWSTemplateFormatVersion: 2010-09-09
Description: |
  VPC and Subnet
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  VpcCidrBlock:
    Description: input vpc cidrblock
    Type: String
    Default: 10.0.0.0/16
# ------------------------------------------------------------#
# MetaData
# ------------------------------------------------------------# 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "VPC and Subnet Configuration"
        Parameters:
          - VpcCidrBlock

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  VPCID:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: false
      EnableDnsSupport: true
      InstanceTenancy: default

# ------------------------------------------------------------#
#  Internet Gateway
# ------------------------------------------------------------#
  INTERNETGATEWAYID:
    Type: AWS::EC2::InternetGateway

  INTERNETGATEWAYATTATCHMENTID:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref INTERNETGATEWAYID
      VpcId: !Ref VPCID

# ------------------------------------------------------------#
#  Route Table
# ------------------------------------------------------------#
  ROUTETABLEID:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
      
  # インターネットゲートウェイをルートテーブルに登録
  INTERNETGATEWAYROUTEID:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref INTERNETGATEWAYID
      RouteTableId: !Ref ROUTETABLEID
      DestinationCidrBlock: 0.0.0.0/0

# ------------------------------------------------------------#
#  Outputs
# ------------------------------------------------------------#
Outputs:
  OUTPUTVPCID:
    Description: vpc id
    Value: !Ref VPCID
    Export: 
      Name: !Sub ${AWS::StackName}-OutputVpcId

  OUTPUTROUTETABLEID:
    Description: route table id
    Value: !Ref ROUTETABLEID
    Export: 
      Name: !Sub ${AWS::StackName}-OutputRouteTableId
